# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7a472982788963bda88cecf0a5f4ddc2"
application_url = "https://062a-45-251-64-200.ngrok-free.app"
embedded = true
name = "mai-pixel"
handle = "mai-pixel"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,write_pixels,write_products,read_products,write_script_tags,read_script_tags"

[auth]
redirect_urls = [
  "https://062a-45-251-64-200.ngrok-free.app/auth/callback",
  "https://062a-45-251-64-200.ngrok-free.app/auth/shopify/callback",
  "https://062a-45-251-64-200.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = true
